/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitest;

/**
 *
 * @author Korisnik
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        math = new javax.swing.JCheckBox();
        informatics = new javax.swing.JCheckBox();
        more = new javax.swing.JTextField();
        sports = new javax.swing.JComboBox();
        total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        math.setText("Matematičar");
        math.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mathStateChanged(evt);
            }
        });

        informatics.setText("Informatičar");
        informatics.setToolTipText("");
        informatics.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                informaticsStateChanged(evt);
            }
        });

        more.setToolTipText("i još...");
        more.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moreKeyTyped(evt);
            }
        });

        sports.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Karatista", "Odbojkaš", "Strastveni kuvar" }));
        sports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsActionPerformed(evt);
            }
        });

        jLabel1.setText("Šta sam to ja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(math, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(informatics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(more)
                            .addComponent(sports, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(math)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(informatics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(more, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mathStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mathStateChanged
        updateTotalLabelText();
    }//GEN-LAST:event_mathStateChanged

    private void informaticsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_informaticsStateChanged
        updateTotalLabelText();
    }//GEN-LAST:event_informaticsStateChanged

    private void moreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moreKeyTyped
        updateTotalLabelText();
    }//GEN-LAST:event_moreKeyTyped

    private void sportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsActionPerformed
        updateTotalLabelText();
    }//GEN-LAST:event_sportsActionPerformed

    private void updateTotalLabelText() {
        String text = "";
        
        if (math.isSelected()) {
            text += "Matematičar, ";
        }
        
        if (informatics.isSelected()) {
            text += "Informatičar, ";
        }
        
        text += sports.getSelectedItem().toString();
        
        String moreText = more.getText();
        
        if (!moreText.isEmpty()) {
            text += "i još " + moreText;
        }
        
        total.setText(text);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox informatics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox math;
    private javax.swing.JTextField more;
    private javax.swing.JComboBox sports;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
